# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Encode-JavaScript-Cyrillic
version:      0.01
version_from: lib/Encode/JavaScript/Cyrillic.pm
installdirs:  site
requires:
    Encode:                        2.12

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
